const CharactersTypes = {
    GET_DEFAULT_CHARACTER: 'GET_DEFAULT_CHARACTER',
    SET_CURRENT_CHARACTER: 'SET_CURRENT_CHARACTER',
    ADD_CHARACTER: 'ADD_CHARACTER', 
    DELETE_CHARACTER: 'DELETE_CHARACTER',
    RESET_CHARACTER: 'RESET_CHARACTER',
    UPDATE_CHARACTER: 'UPDATE_CHARACTER',
    MOVE_BODY_PART: 'MOVE_BODY_PART',
    MOVE_CHARACTER: 'MOVE_CHARACTER'

}

export default CharactersTypes;