const CharactersTypes = {
    GET_DEFAULT_CHARACTER: 'GET_DEFAULT_CHARACTER',
    SET_CURRENT_CHARACTER: 'SET_CURRENT_CHARACTER',
    ADD_CHARACTER: 'ADD_CHARACTER', 
    DELETE_CHARACTER: 'DELETE_CHARACTER',
    RESET_CHARACTER: 'RESET_CHARACTER'

}

export default CharactersTypes;