const ScenesTypes = {
    ADD_SCENE: 'ADD_SCENE',
    DELETE_SCENE: 'DELETE_SCENE',
    ADD_CHAR_TO_SCENE: 'ADD_CHAR_TO_SCENE',
    DELETE_CHAR_FROM_SCENE: 'DELETE_CHAR_FROM_SCENE',
    SET_BACKGROUND: 'SET_BACKGROUND',
}

export default ScenesTypes;